server:
  port: 8011
spring:
  application:
    name: mq-consumer
  datasource:
    url: jdbc:mysql://localhost:3306/a33?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.111.114
    port: 5672
    username: zhumeng
    password: 123456
    virtual-host: /
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        service: mq-consumer
  # 配置邮件
mail:
  configs:
    # 账号
    - username: 2046188606@qq.com
      password: cdltejgfvjoabhhd
      host: smtp.qq.com
      port: 25
      protocol: smtp
      default-encoding: UTF-8
    # 账号A
#    - username: fapiaoa@QQ.com
#      password: 123456
#      host: smtp.qq.com
#      port: 25
#      protocol: smtp
#      default-encoding: UTF-8
  #  mail:
  #    host: smtp.qq.com
  #    username: 2046188606@qq.com
  #    password: cdltejgfvjoabhhd
  #    default-encoding: UTF-8
  #    listener:
#      simple:
#        prefetch: 1
#        retry:
#          enabled: true #开启消费者失败重试
#          initial-interval: 1000 #初识的失败等待时长为1 秒
#          multiplier: 2 #下次失败的等待时长倍数，下次等待时长 = multiplier * last-interval
#          max-attempts: 3 #最大重试次数
#          stateless: true # true无状态; false有状态。如果业务中包含事务，这里改为false

