server:
  port: 8006
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/a33?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user
  redis: #redis缓存配置
    host: 192.168.111.114
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1  #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0
  main:
    allow-bean-definition-overriding: true




feign:
  client:
    config:
      default:
        ribbon:
          enabled: true

#feign:
#  client:
#    config:
#      ## default 设置的全局超时时间，指定服务名称可以设置单个服务的超时时间
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#      ## 为serviceC这个服务单独配置超时时间
#      serviceC:
#        connectTimeout: 30000
#        readTimeout: 30000

#日志配置

