server:
  port: 8020
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/a33?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: care
  main:
    allow-bean-definition-overriding: true
feign:
  client:
    config:
      default:
        ribbon:
          enabled: true
zookeeper:
  url: localhost:2181
  groupName: blessing-elastic-job


