server:
  port: 8020
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/a33?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: care
  main:
    allow-bean-definition-overriding: true
feign:
  client:
    config:
      default:
        ribbon:
          enabled: true
zookeeper:
  url: localhost:2181
  groupName: blessing-elastic-job
# 阿里云oss对象存储
aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5tPqmkuAZMN8cM5vzWLV
    accessKeySecret: mLO40ZQh87dH3LIJodnnJPsOCLsai9
    bucketName: jerry273

