server:
  port: 8009
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/a33?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: manage
  redis: #redis缓存配置
    host: 192.168.111.114
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1  #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0
mybatis-plus:
  mapper-locations: classpath*:xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
