server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes:
        - id: manage
          uri: lb://manage
          predicates:
              - Path=/manage/**
        - id: personal
          uri: lb://personal
          predicates:
              - Path=/personal/**
        - id: sms
          uri: lb://sms
          predicates:
            - Path=/sms/**
        - id: user
          uri: lb://user
          predicates:
              - Path=/user/**
        - id: written
          uri: lb://written
          predicates:
              - Path=/written/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            maxAge: 1800

          #使用RewritePath过滤器将请求的路径重写为后端服务期望的路径格式
#          filters:
#            - RewritePath=/another/(?<path>.*), /$\{path}
#      discovery:
#        locator:
#          enabled: true
# 配置了HTTP客户端（httpclient）的SSL设置，用于处理HTTPS请求时的证书验证问题
#      httpclient:
#        ssl:
#          useInsecureTrustManager: true
