server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes:
#        - id: employee # 路由唯一标识
#          # uri: lb://employee # 路由目标地址
#          uri: http://localhost:8888 # 路由目标地址
#          predicates: # 判断请求是否符合规则
#            - Path=/manage/**  #路径断言,符合规则就会代理到uri
        - id: sms
          uri: lb://sms
          predicates:
            - Path=/sms/**
          #使用RewritePath过滤器将请求的路径重写为后端服务期望的路径格式
#          filters:
#            - RewritePath=/another/(?<path>.*), /$\{path}
      discovery:
        locator:
          enabled: true
# 配置了HTTP客户端（httpclient）的SSL设置，用于处理HTTPS请求时的证书验证问题
#      httpclient:
#        ssl:
#          useInsecureTrustManager: true
