server:
  port: 8010
spring:
  application:
    name: mq-service
  datasource:
    url: jdbc:mysql://localhost:3306/a33?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.111.114
    port: 5672
    username: zhumeng
    password: 123456
    virtual-host: /
    # 配置消息发送成功和失败的回调
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        service: mq-service